sonar.projectKey=anischamekh_MyStartUp_PFA
sonar.organization=anischamekh
sonar.host.url=https://sonarcloud.io

sonar.sources=microservices,frontend/src
sonar.java.binaries=microservices/**/target/classes
sonar.exclusions=**/node_modules/**,**/target/**,**/*.spec.ts,**/dist/**,**/.angular/**
