sonar.projectKey=anischamekh_MyStartUp_PFA
sonar.organization=anischamekh
sonar.host.url=https://sonarcloud.io

sonar.sources=microservices,frontend/src
sonar.java.binaries=microservices/**/target/classes
sonar.exclusions=**/node_modules/**,**/target/**,**/*.spec.ts,**/dist/**,**/.angular/**
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=microservices/common-lib/target/site/jacoco/jacoco.xml,microservices/auth-service/target/site/jacoco/jacoco.xml,microservices/hrm-service/target/site/jacoco/jacoco.xml,microservices/project-service/target/site/jacoco/jacoco.xml,microservices/chatbot-service/target/site/jacoco/jacoco.xml
sonar.coverage.inclusions=**/service/**,**/security/**,**/common/security/**
sonar.coverage.exclusions=**/*Test.java,**/test/**,**/entity/**,**/dto/**,**/config/**
